package modal;
// Generated 15 Mar, 2019 4:10:10 PM by Hibernate Tools 5.2.3.Final

/**
 * JcAccessories generated by hbm2java
 */
public class JcAccessories implements java.io.Serializable {

	private int jobcardNumber;
	private boolean toolkit;
	private boolean spareWheel;
	private boolean jackAndHandle;
	private boolean mats;
	private boolean wheelCaps;
	private boolean mudFlaps;
	private boolean sterio;
	private boolean clockOrPhoto;
	private String other;
	private String image;

	
	public int getJobcardNumber() {
		return this.jobcardNumber;
	}

	public void setJobcardNumber(int jobcardNumber) {
		this.jobcardNumber = jobcardNumber;
	}


	public boolean isToolkit() {
		return this.toolkit;
	}

	public void setToolkit(boolean toolkit) {
		this.toolkit = toolkit;
	}

	public boolean isSpareWheel() {
		return this.spareWheel;
	}

	public void setSpareWheel(boolean spareWheel) {
		this.spareWheel = spareWheel;
	}

	public boolean isJackAndHandle() {
		return this.jackAndHandle;
	}

	public void setJackAndHandle(boolean jackAndHandle) {
		this.jackAndHandle = jackAndHandle;
	}

	public boolean isMats() {
		return this.mats;
	}

	public void setMats(boolean mats) {
		this.mats = mats;
	}

	public boolean isWheelCaps() {
		return this.wheelCaps;
	}

	public void setWheelCaps(boolean wheelCaps) {
		this.wheelCaps = wheelCaps;
	}

	public boolean isMudFlaps() {
		return this.mudFlaps;
	}

	public void setMudFlaps(boolean mudFlaps) {
		this.mudFlaps = mudFlaps;
	}

	public boolean isSterio() {
		return this.sterio;
	}

	public void setSterio(boolean sterio) {
		this.sterio = sterio;
	}

	public boolean isClockOrPhoto() {
		return this.clockOrPhoto;
	}

	public void setClockOrPhoto(boolean clockOrPhoto) {
		this.clockOrPhoto = clockOrPhoto;
	}

	public String getOther() {
		return this.other;
	}

	public void setOther(String other) {
		this.other = other;
	}

	public String getImage() {
		return this.image;
	}

	public void setImage(String image) {
		this.image = image;
	}

}
